### ISSUE TITLE
Virus total Scan results = negative

### ISSUE THREAD

**Issue by aimarket** [daijro/shortlyai-scraper#3]
![image](https://user-images.githubusercontent.com/32007930/176836754-87ad1d3c-f7c0-42b8-a955-452a4fb98b75.png)

**Comment by daijro** [comment]
Hello, the binaries included in the msi installer file are built directly from the source code using PyInstaller in a fresh Windows VM. Some sensitive anti viruses might falsely flag this file because it is not signed, or because PyInstaller is known to cause false positives.

If you would like to run the source code directly, the instructions are included [here](https://github.com/daijro/EssayGen#installation). Thanks!
